name: Deploy Helion Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # 3. Install dependencies
      - run: npm ci

      # 4. Build Helion library
      - run: npm run build:lib

      # 5. Make a copy of the examples dir in public for the Astro GitHub pages site
      - run: npm run build:examples

      # 6. Build Astro docs
      - name: Build Astro docs
        working-directory: docs
        run: npm run docs:build

      # 7. Deploy to GitHub Pages (root or docs folder)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          publish_branch: gh-pages
          force_orphan: true
